# Form implementation generated from reading ui file 'd:\python\youtube-loader\src\ui\DashAudioStreamsWidget.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DashAudioStreamsWidget(object):
    def setupUi(self, DashAudioStreamsWidget):
        DashAudioStreamsWidget.setObjectName("DashAudioStreamsWidget")
        DashAudioStreamsWidget.resize(670, 140)
        DashAudioStreamsWidget.setMinimumSize(QtCore.QSize(670, 140))
        DashAudioStreamsWidget.setMaximumSize(QtCore.QSize(670, 140))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DashAudioStreamsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DashAudioStreamsWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tracks = QtWidgets.QComboBox(self.groupBox)
        self.tracks.setMinimumSize(QtCore.QSize(500, 0))
        self.tracks.setObjectName("tracks")
        self.verticalLayout.addWidget(self.tracks)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(50, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.mimeTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.mimeTypeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.mimeTypeLabel.setObjectName("mimeTypeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mimeTypeLabel)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.audioBitrateLabel = QtWidgets.QLabel(self.groupBox)
        self.audioBitrateLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.audioBitrateLabel.setObjectName("audioBitrateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.audioBitrateLabel)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.audioCodecLabel = QtWidgets.QLabel(self.groupBox)
        self.audioCodecLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.audioCodecLabel.setObjectName("audioCodecLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.audioCodecLabel)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(DashAudioStreamsWidget)
        QtCore.QMetaObject.connectSlotsByName(DashAudioStreamsWidget)

    def retranslateUi(self, DashAudioStreamsWidget):
        _translate = QtCore.QCoreApplication.translate
        DashAudioStreamsWidget.setWindowTitle(_translate("DashAudioStreamsWidget", "Form"))
        self.groupBox.setTitle(_translate("DashAudioStreamsWidget", "Выберите аудио поток"))
        self.label_2.setText(_translate("DashAudioStreamsWidget", "mime type:"))
        self.mimeTypeLabel.setText(_translate("DashAudioStreamsWidget", "n/a"))
        self.label_4.setText(_translate("DashAudioStreamsWidget", "Битрейт:"))
        self.audioBitrateLabel.setText(_translate("DashAudioStreamsWidget", "n/a"))
        self.label_5.setText(_translate("DashAudioStreamsWidget", "Аудио кодек:"))
        self.audioCodecLabel.setText(_translate("DashAudioStreamsWidget", "n/a"))
