# Form implementation generated from reading ui file 'd:\python\youtube-loader\src\ui\DashVideoStreamsWidget.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DashVideoStreamsWidget(object):
    def setupUi(self, DashVideoStreamsWidget):
        DashVideoStreamsWidget.setObjectName("DashVideoStreamsWidget")
        DashVideoStreamsWidget.resize(670, 160)
        DashVideoStreamsWidget.setMinimumSize(QtCore.QSize(670, 160))
        DashVideoStreamsWidget.setMaximumSize(QtCore.QSize(670, 160))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DashVideoStreamsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DashVideoStreamsWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tracks = QtWidgets.QComboBox(self.groupBox)
        self.tracks.setMinimumSize(QtCore.QSize(500, 0))
        self.tracks.setObjectName("tracks")
        self.verticalLayout.addWidget(self.tracks)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(50, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.videoResolutionLabel = QtWidgets.QLabel(self.groupBox)
        self.videoResolutionLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.videoResolutionLabel.setObjectName("videoResolutionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.videoResolutionLabel)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.videoFpsLabel = QtWidgets.QLabel(self.groupBox)
        self.videoFpsLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.videoFpsLabel.setObjectName("videoFpsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.videoFpsLabel)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.videoCodecLabel = QtWidgets.QLabel(self.groupBox)
        self.videoCodecLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.videoCodecLabel.setObjectName("videoCodecLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.videoCodecLabel)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.mimeTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.mimeTypeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.mimeTypeLabel.setObjectName("mimeTypeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mimeTypeLabel)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(DashVideoStreamsWidget)
        QtCore.QMetaObject.connectSlotsByName(DashVideoStreamsWidget)

    def retranslateUi(self, DashVideoStreamsWidget):
        _translate = QtCore.QCoreApplication.translate
        DashVideoStreamsWidget.setWindowTitle(_translate("DashVideoStreamsWidget", "Form"))
        self.groupBox.setTitle(_translate("DashVideoStreamsWidget", "Выберите видео поток"))
        self.label_2.setText(_translate("DashVideoStreamsWidget", "Разрешение видео:"))
        self.videoResolutionLabel.setText(_translate("DashVideoStreamsWidget", "n/a"))
        self.label_5.setText(_translate("DashVideoStreamsWidget", "fps:"))
        self.videoFpsLabel.setText(_translate("DashVideoStreamsWidget", "n/a"))
        self.label_3.setText(_translate("DashVideoStreamsWidget", "Видео кодек:"))
        self.videoCodecLabel.setText(_translate("DashVideoStreamsWidget", "n/a"))
        self.label_4.setText(_translate("DashVideoStreamsWidget", "mime type:"))
        self.mimeTypeLabel.setText(_translate("DashVideoStreamsWidget", "n/a"))
