# Form implementation generated from reading ui file 'd:\python\youtube-loader\src\ui\OutProcessWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets, QtGui


class Ui_OutProcessWindow(object):
    def setupUi(self, OutProcessWindow):
        OutProcessWindow.setObjectName("OutProcessWindow")
        OutProcessWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        OutProcessWindow.setFixedSize(700, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/img/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        OutProcessWindow.setWindowIcon(icon)
        OutProcessWindow.setWindowFlag(QtCore.Qt.WindowType.SubWindow)
        OutProcessWindow.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(OutProcessWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(OutProcessWindow)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.okButton = QtWidgets.QPushButton(OutProcessWindow)
        self.okButton.setEnabled(False)
        self.okButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.okButton.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)

        self.retranslateUi(OutProcessWindow)
        QtCore.QMetaObject.connectSlotsByName(OutProcessWindow)

    def retranslateUi(self, OutProcessWindow):
        _translate = QtCore.QCoreApplication.translate
        OutProcessWindow.setWindowTitle(_translate("OutProcessWindow", "Выполнение"))
        self.okButton.setText(_translate("OutProcessWindow", "Ok"))
